### ISSUE TITLE
com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by amo222lpatil** [hansemannn/titanium-firebase-auth#7] opened 2018-08-09 11:52 UTC
On android I'm using: 

Ti SDK : 7.2.0.GA
firebase.core : 2.2.0
firebase.auth : 1.0.1
ti.playservices : 11.0.40
hyperloop : 3.0.5
Alloy project

**index.xml**
```xml
<Alloy>
	<Window id="mainWin">
		<View id="mainView">
			<Button id="loginButton" onClick="login">Login</Button>
		</View>
	</Window>
</Alloy>
```

**index.js**
```js
$.mainWin.open();
function login() {
	Ti.API.info("[index] >> [login]");
	
         Ti.API.info("[index] >> [login] >> before Requiring firbase.core");
	var Firebase = require('firebase.core');
	Firebase.configure();

	Ti.API.info("[index] >> [login] >> after configure firbase.core ");
	var FirebaseAuth = require('firebase.auth');
	Ti.API.info("[index] >> [login] >> After requiring firbase.auth");
	
         Ti.API.info("[index] >> [login] >> FirbaseAuth vaariable contains : " + JSON.stringify(FirebaseAuth));

	Ti.API.info("[index] >> [login] >> calling to signINWithEmail");
	FirebaseAuth.signInWithEmail({
		email : 'dfjkdnskj@fjndjfk.com',
		password : '*********',
		callback : function(e) {
			Ti.API.info("[index] >> [login] >> in callback.");
			if (!e.success) {
				Ti.API.error('Error: ' + e.error);
				return;
			}

			Ti.API.info('Success!');
			Ti.API.info(e.user);
		}
	});
}
```

I called login method after login button is pressed. I do Firebase API's call after app finished launching.
then also it given error below:

```appceleratorconsole
-- Start application log -----------------------------------------------------
[INFO] :   TiApplication: (main) [0,0] checkpoint, app created.
[INFO] :   TiApplication: (main) [65,65] Titanium 7.1.0 (2018/03/14 13:40 undefined)
[INFO] :   MultiDex: VM with version 2.1.0 has multidex support
[INFO] :   MultiDex: install
[INFO] :   MultiDex: VM has multidex support, MultiDex support library is disabled.
[WARN] :   TiAndroid: (main) [1162,1227] Application instance no longer available. Unable to get current activity.
[WARN] :   TiAndroid: (main) [1,1228] Application instance no longer available. Unable to get current activity.
[WARN] :   TiAndroid: (main) [0,1228] Application instance no longer available. Unable to get current activity.
[INFO] :   TiApplication: (main) [31,1259] Titanium Javascript runtime: v8
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
[INFO] :   DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = com.mindstix.googleAuth.GoogleauthActivity@7c2e
[INFO] :   Adreno: QUALCOMM build                   : 7a841e6, I43097da1fb
[INFO] :   Adreno: Build Date                       : 05/10/16
[INFO] :   Adreno: OpenGL ES Shader Compiler Version: XE031.06.00.02
[INFO] :   Adreno: Local Branch                     : mybranch19687176
[INFO] :   Adreno: Remote Branch                    : quic/LA.BR.1.3.3.c4
[INFO] :   Adreno: Remote Branch                    : NONE
[INFO] :   Adreno: Reconstruct Branch               : NOTHING
[INFO] :   OpenGLRenderer: Initialized EGL, version 1.4
[INFO] :   ACS Login Results for environment `development`:
[INFO] :   [object Object]
[TRACE] :  updating tiapp metadata with Appcelerator Platform...
[TRACE] :  Uploaded tiapp metadata with Appcelerator Platform!
[INFO] :   ViewRootImpl: finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=2 eventTime = 3536490 downTime = 3536490 title= com.mindstix.googleAuth/org.appcelerator.titanium.TiActivity
[INFO] :   ViewRootImpl: finishMotionEvent: handled = true stage=10: View Post IME stage,inputElapseTime=1 eventTime = 3539173 downTime = 3539173 title= com.mindstix.googleAuth/org.appcelerator.titanium.TiActivity
[INFO] :   [index] >> [login]
[INFO] :   [index] >> [login] >> before Requiring firbase.core
[INFO] :   [index] >> [login] >> after configure firbase.core
[INFO] :   [index] >> [login] >> After requiring firbase.auth
[INFO] :   [index] >> [login] >> FirbaseAuth variable contains : {}
[INFO] :   [index] >> [login] >> calling to signInWithEmail
[WARN] :   W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference
[WARN] :   W/System.err: 	at firebase.auth.TitaniumFirebaseAuthModule.signInWithEmail(TitaniumFirebaseAuthModule.java:141)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:962)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1186)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:394)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:148)
[WARN] :   W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5582)
[WARN] :   W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] :  TiExceptionHandler: (main) [10909,10909] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,10909] - In /alloy/controllers/index.js:71,18
[ERROR] :  TiExceptionHandler: (main) [0,10909] - Message: Uncaught Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference
[ERROR] :  TiExceptionHandler: (main) [0,10909] - Source:     FirebaseAuth.signInWithEmail({
[ERROR] :  V8Exception: Exception occurred at /alloy/controllers/index.js:71: Uncaught Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference
```

**Comment by hansemannn** [comment] 2018-08-09 11:54
Duplicate of #5 and #6. Please do not create new issues, this can be seen as spam.

**Closed by hansemannn** 2018-08-09 11:54 UTC

**Comment by amo222lpatil** [comment] 2018-08-09 12:00
where i do mistake ?

**Comment by amo222lpatil** [comment] 2018-08-09 12:39
Please reply
